# Generated by Django 5.1.4 on 2024-12-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='title',
        ),
    ]
