# Generated by Django 5.1.4 on 2024-12-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_mail_name_remove_mail_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
